services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DsWebCrawlerBundle\Guard\DefaultDataResourceGuard:
        tags:
            - {name: dynamic_search.context_guard }