services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DsWebCrawlerBundle\Normalizer\ResourceNormalizer:
        tags:
            - { name: dynamic_search.resource_normalizer, identifier: web_crawler_resource_normalizer, data_provider: web_crawler }