services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DsWebCrawlerBundle\Normalizer\DefaultResourceNormalizer:
        tags:
            - { name: dynamic_search.resource_normalizer, identifier: web_crawler_default_resource_normalizer, data_provider: web_crawler }

    DsWebCrawlerBundle\Normalizer\LocalizedResourceNormalizer:
        tags:
            - { name: dynamic_search.resource_normalizer, identifier: web_crawler_localized_resource_normalizer, data_provider: web_crawler }