services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DsWebCrawlerBundle\Transformer\HttpResponseHtmlDataTransformer:
        tags:
            - { name: dynamic_search.transformer.dispatcher, priority: 10, identifier: http_response_html }

    DsWebCrawlerBundle\Transformer\HttpResponsePdfDataTransformer:
        tags:
            - { name: dynamic_search.transformer.dispatcher, priority: 5, identifier: http_response_pdf }


    DsWebCrawlerBundle\Transformer\Field\Html\DocumentIdExtractor:
        tags:
            - { name: dynamic_search.transformer.field, identifier: resource_document_id_extractor, data_transformer: http_response_html }

    DsWebCrawlerBundle\Transformer\Field\Pdf\DocumentIdExtractor:
        tags:
            - { name: dynamic_search.transformer.field, identifier: resource_document_id_extractor, data_transformer: http_response_pdf }

    DsWebCrawlerBundle\Transformer\Field\Common\UriExtractor:
        tags:
            - { name: dynamic_search.transformer.field, identifier: resource_uri_extractor, data_transformer: http_response_html }
            - { name: dynamic_search.transformer.field, identifier: resource_uri_extractor, data_transformer: http_response_pdf }

    DsWebCrawlerBundle\Transformer\Field\Common\HostExtractor:
        tags:
            - { name: dynamic_search.transformer.field, identifier: resource_host_extractor, data_transformer: http_response_html }
            - { name: dynamic_search.transformer.field, identifier: resource_host_extractor, data_transformer: http_response_pdf }

    DsWebCrawlerBundle\Transformer\Field\Html\LanguageExtractor:
        tags:
            - { name: dynamic_search.transformer.field, identifier: resource_language_extractor, data_transformer: http_response_html }

    DsWebCrawlerBundle\Transformer\Field\Pdf\LanguageExtractor:
        tags:
            - { name: dynamic_search.transformer.field, identifier: resource_language_extractor, data_transformer: http_response_pdf }

    DsWebCrawlerBundle\Transformer\Field\Html\MetaExtractor:
        tags:
            - { name: dynamic_search.transformer.field, identifier: resource_meta_extractor, data_transformer: http_response_html }

    DsWebCrawlerBundle\Transformer\Field\Html\HtmlTagExtractor:
        tags:
            - { name: dynamic_search.transformer.field, identifier: resource_html_tag_content_extractor, data_transformer: http_response_html }

    DsWebCrawlerBundle\Transformer\Field\Html\TextExtractor:
        tags:
            - { name: dynamic_search.transformer.field, identifier: resource_text_extractor, data_transformer: http_response_html }

    DsWebCrawlerBundle\Transformer\Field\Pdf\TextExtractor:
        tags:
            - { name: dynamic_search.transformer.field, identifier: resource_text_extractor, data_transformer: http_response_pdf }

    DsWebCrawlerBundle\Transformer\Field\Html\TitleExtractor:
        tags:
            - { name: dynamic_search.transformer.field, identifier: resource_title_extractor, data_transformer: http_response_html }

    DsWebCrawlerBundle\Transformer\Field\Pdf\TitleExtractor:
        tags:
            - { name: dynamic_search.transformer.field, identifier: resource_title_extractor, data_transformer: http_response_pdf }