imports:
    - { resource: services/*.yml }

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DsWebCrawlerBundle\Configuration\Configuration: ~

    DsWebCrawlerBundle\Service\CrawlerStateService: ~

    DsWebCrawlerBundle\Service\FileWatcherService: ~

    DsWebCrawlerBundle\Service\CrawlerService: ~

    DsWebCrawlerBundle\Registry\EventSubscriberRegistry: ~

    DsWebCrawlerBundle\Twig\Extension\CrawlerExtension:
        tags:
            - { name: twig.extension }